---
name: Release

on:
  workflow_dispatch:

# we do not want more than one release workflow executing at the same time, ever
concurrency:
  group: release
  # cancelling in the middle of a release would create incomplete releases
  # so cancel-in-progress is false
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Install Conda environment from environment.yml
        # Just for python / poetry really
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true
          environment-file: conda-linux-64.lock
          environment-name: glasswool
          channels: conda-forge
            nodefaults

      # Change env to glasswool to pick up poetry from there
      - name: activate mamba environment
        run: |
          mamba env export
          python -V -V

      #      - uses: syphar/restore-pip-download-cache@v1
      #        with:
      #          requirement_files: poetry.lock
      #          custom_cache_key_element: no-backends-${{ steps.install_python.outputs.python-version }}
      #
      #      - uses: syphar/restore-virtualenv@v1
      #        with:
      #          requirement_files: poetry.lock
      #          custom_cache_key_element: core

      - name: run semantic-release
        run: ./ci/release/run.sh
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
